#!/bin/bash

set -e

base_dir="$(dirname "$(readlink -f "$0")")"
base_dir="${base_dir%/}"

cd "$base_dir"

echo
tools/apktool/download-latest
echo
tools/dexpatcher/download-latest
echo
echo "NOTE: dex2jar is not actively maintained."
echo
